### ISSUE TITLE
In Node.js v20.11.0, it's not possible to match directories containing emojis.

### ISSUE THREAD

**Issue by Nisekoi5** [mrmlnc/fast-glob#436] opened 2024-02-05 10:24 UTC
### Environment

  * OS Version: Windows11
  * Node.js Version: v20.11.0

### Actual behavior
Cannot be matched in file

### Expected behavior
Match files correctly

### Steps to reproduce
Directory Structure
```
scripts
│  og-template.svg
│  post-docs.ts
│  update.ts
│
├─types
│      changelog.d.ts
│      index.d.ts
│      metadata.d.ts
│
├─utils
│      index.ts
│
└─🪄test
        testtest.ts
```
Run the following code using nodejs v20.11.0 , Got the following result
The contents of the `🪄test` directory are not included in it
```
[
  'scripts/post-docs.ts',
  'scripts/update.ts',
  'scripts/types/changelog.d.ts',
  'scripts/types/index.d.ts',
  'scripts/types/metadata.d.ts',
  'scripts/utils/index.ts'
]
[
  './scripts/post-docs.ts',
  './scripts/update.ts',
  './scripts/utils/index.ts',
  './scripts/types/changelog.d.ts',
  './scripts/types/index.d.ts',
  './scripts/types/metadata.d.ts'
]
```
Doing nothing, I just switched the version of nodejs to v18.19.0 and I got the following result
```
[
  'scripts/post-docs.ts',
  'scripts/update.ts',
  'scripts/types/changelog.d.ts',
  'scripts/types/index.d.ts',
  'scripts/types/metadata.d.ts',
  'scripts/utils/index.ts',
  'scripts/🪄test/testtest.ts'
]
[
  './scripts/post-docs.ts',
  './scripts/update.ts',
  './scripts/types/changelog.d.ts',
  './scripts/types/index.d.ts',
  './scripts/types/metadata.d.ts',
  './scripts/utils/index.ts',
  './scripts/🪄test/testtest.ts'
]
```
## code

```
import fg from 'fast-glob'
const dir = './'
const pattern = [
    "scripts/**/*.ts",
    "./scripts/**/*.ts",

]
async function run() {
    let files
    for (const p of pattern) {
        files = await fg(p, {
            onlyFiles: true,
            cwd: dir,
            ignore: [
                '_*',
                'dist',
                'node_modules',
            ],
        })
        console.log(files)
    }

}
run()
```

**Comment by mrmlnc** [comment] 2024-11-23 12:15
I can confirm that the problem is reproducible on Windows for 20.11.0 and has been fixed in 20.12.0.

**Closed by mrmlnc** 2024-11-23 12:15 UTC
