### ISSUE TITLE
EACCES exception raised for directories without read permissions

### ISSUE THREAD

**Issue by gnikit** [mrmlnc/fast-glob#334] opened 2021-11-14 16:09 UTC
### Environment

  * OS Version: Linux x64 5.4.0-90-generic
  * Node.js Version: v14.18.1

### Actual behavior

fast-glob throws a `EACCES` or hangs (i.e. fails silently) depending on if `suppressErrors` is set for directory with inadequate read permissions.

### Expected behavior

Ignore directory and continue glob search, or have an option to ignore EACCES errors.

### Steps to reproduce

  1. Create a some directories `mkdir -p temp/{public,private}`
  2. Revoke read permissions to one `chmod -r temp/private`
  3. Run code snippet

### Code sample

I encountered this in TypeScript but it's the same code.

```typescript
import * as fg from 'fast-glob';

const globIncPaths: string[] = fg.sync('temp/**', {
  cwd: 'your/cwd',
  onlyDirectories: true,
  suppressErrors: false, // set to true to trigger a race condition
});
```

### Additional information

I have found a fix using `glob` and setting the option `{ strict: false }`. Is there something equivalent for `fast-glob`?

**Comment by mrmlnc** [comment] 2022-09-08 06:27
Hm, I don't see a problem here.

When the user specifies the `suppressErrors` option, errors that occur when reading directories are ignored. As far as I can see, in the `node-glob` package, the `strict` option has exactly the same behavior.

I can't reproduce the problem on Windows and Ubuntu (under WSL).

Directories:

```js
$ tree temp
temp
├── private [error opening dir]  // d-wx-wx-wx
└── public
    └── file.txt

2 directories, 1 file
```

Code:

```js
const fg = require('fast-glob');

(async () => {
	// The same behaviour with the synchronous version.
	const entries = await fg('temp/**', {
		cwd: '/mnt/d/OpenSource/fast-glob', // wsl
		onlyFiles: false,
		suppressErrors: true
	});

	console.dir(entries, { colors: true });
})();
```

Result:

```js
[ 'temp2/private', 'temp2/public', 'temp2/public/file.txt' ]
```

Also result for the `glob` package:

```js
// Output to the console from these lines:
// https://github.com/isaacs/node-glob/blob/af57da21c7722bb6edb687ccd4ad3b99d3e7a333/sync.js#L338-L344

glob error Error: EACCES: permission denied, scandir '/mnt/d/OpenSource/fast-glob/temp2/private'
    at Object.readdirSync (node:fs:1442:3)
    at GlobSync._readdir (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:288:46)
    at GlobSync._readdirInGlobStar (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:267:20)
    at GlobSync._readdir (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:276:17)
    at GlobSync._processGlobStar (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:350:22)
    at GlobSync._process (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:130:10)
    at GlobSync._processGlobStar (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:383:10)
    at GlobSync._process (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:130:10)
    at new GlobSync (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:45:10)
    at Function.globSync [as sync] (/mnt/d/OpenSource/fast-glob/node_modules/glob/sync.js:23:10) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/mnt/d/OpenSource/fast-glob/temp2/private'
}

// The first entry related to an issue #47
[ 'temp2', 'temp2/private', 'temp2/public', 'temp2/public/file.txt' ]
```

---

Well, I close this issue. Let me know if I missed something.

**Closed by mrmlnc** 2022-09-08 06:27 UTC
Labels: Type: Need More Details

**Comment by gnikit** [comment] 2022-09-08 14:19
Thanks for getting back to me @mrmlnc. Whatever was causing this I can't reproduce it either with node v18.7.0. Happy for this to close.
